# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('subject', models.CharField(max_length=50, verbose_name='问题')),
                ('message', models.CharField(max_length=100, verbose_name='信息')),
            ],
            options={
                'verbose_name_plural': '留言信息',
                'verbose_name': '留言信息',
            },
        ),
    ]
